Update jinja.py
When I was trying to use this library, I was getting import error here "ImportError: cannot import name 'Markup' from 'jinja2'". After changing to jinja2.utils, it works well.